### ISSUE TITLE
Load fixtures classes from tests (composer autoload)

### ISSUE THREAD

**Issue by LubosRemplik** [LubosRemplik/CakePHP-Fixtures#1]
Currently I am not able to load class from tests folder because of wrong composer autoload settings (I think). When I want to use, I have to copy the fixture from tests to src folder and rename namespace.

Help needed.

**Comment by mtancoigne** [comment]
Maybe you should add your fixture folder to composer.json:

```json
{
    "autoload": {
        "psr-4": {
            "App\\": "src",
            // Here
            "Fixtures\\": "./Fixtures"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests",
            // OR Here
            "Fixtures\\": "./Fixtures"
        }
    }
}
```

**Comment by LubosRemplik** [comment]
It works for me now, thanks for help @mtancoigne
